Task 3
DsiDerInKo/OOP pull request #5
Opened 2022-11-28 18:48 UTC by DsiDerInKo

2023-02-13 13:48 UTC, MihailCCfit requested changes

2023-02-13 13:48 UTC, MihailCCfit commented on Task1/src/main/java/bushuev/ari/MainClass.java
> +public class MainClass {
Убери `MainClass` и `main`

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return null;
Измени, чтобы если что массив новый возвращался

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +            if (o.equals(iter.next())) iter.remove();
Удаляет первое вхождение числа, а не все числа, согласно документации выше

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +    public boolean remove() {
Док где?

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return true;
true, согласно доку, только если массив был изменён.

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return true;
И ещё, addAll добавляет всё в **ТВОЮ** коллекцию (в конец списка), а не в переданную.

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        while (i != (index)) {
попробуй написать циклом `for` по переменной `i`.

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        while (i != (index)) {
аналогично предыдущему

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        while (i != (index)) {
И это

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        while (!o.equals(node.value)) {
Сделай с помощью `for` по твоему объекту `this`, будет короче и легче изменять будет логику списка.

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return i;
-1 если не нашлось

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +    public int indexOf(Object o) {
А вдруг объект `null`?
Прочитай док к этому методу, который написан выше

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +    public int lastIndexOf(Object o) {
Посмотри на предыдущие замечания

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +                listSize--;
Странно выглядит, что `iter.remove` выполнился и приходится отдельно уменьшать `listSize`

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +            if (!c.contains(iter.next())){
Посоветовал бы сделать из изначальной коллекции - множество (`Set`) тогда нахождение элемента будет быстрым. Возможно и в removeAll то же можно так оптимизировать.

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return true;
Выглядит как подгон). Не всегда true будет

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +    public boolean removeAll(Collection c) {
Смотри `retainAll`

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +    public boolean containsAll(Collection c) {
Подумай про `Set` мб можно с ним сделать. Если нет, то почему?

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/test/java/is/bushuev/TestMyList.java
> +        list1.add(12);
Порекомендовал бы просто сделать List list = List.of(12,13,14,20), а потом обоим его передавать. Дублирование кода не очень удобно для исправления багов и модификации

2023-02-13 13:48 UTC, MihailCCfit commented on Task3/src/test/java/is/bushuev/TestMyList.java
> +    }
Ещё проверь возвращаемы значения функций `add` `remove`, и некоторых других. Ведь они имеют возвращаемое значение, которое задокументировано.

2023-02-21 14:53 UTC, MihailCCfit requested changes
В общем - нужно либо выключить reviewdog, либо форматировать код как надо. Второе и первое делается не сложно, но здесь ничего из этого не наблюдалось, а проверять такой код с замечаниями практически невозможно

2023-02-21 14:53 UTC, MihailCCfit commented on Task3/src/main/java/is/bushuev/MyList.java
> +        return a;
Согласно документации (буквально выше названия этого метода), должен создаться и вернуться новый массив, если переданный не может всё вместить.

2023-03-05 17:44 UTC, MihailCCfit approved these changes

2023-03-05 17:44 UTC, MihailCCfit commented on Task3/src/test/java/is/bushuev/TestMyList.java
> +        if (list1.size() != list2.size()) return false;
Лучше бы сделать с интреом и фигурнными скобками

2023-03-05 18:08 UTC, DsiDerInKo commented
MyList (after long time)

2023-03-05 18:08 UTC, merged